version: '3.9'

services:
  #MongoDB service
  mongo_db:
    container_name: mongo_db_todo
    image: mongo:latest
    restart: always
    ports:
      - 2718:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
